// Generated by the protocol buffer compiler.  DO NOT EDIT!

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "OpenStack.NeutronServer.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace cloudos {
namespace config {
namespace openstack {

namespace {

const ::google::protobuf::Descriptor* NeutronServer_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NeutronServer_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_OpenStack_2eNeutronServer_2eproto() {
  protobuf_AddDesc_OpenStack_2eNeutronServer_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "OpenStack.NeutronServer.proto");
  GOOGLE_CHECK(file != NULL);
  NeutronServer_descriptor_ = file->message_type(0);
  static const int NeutronServer_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NeutronServer, host_ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NeutronServer, public_ip_pool_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NeutronServer, ssl_settings_),
  };
  NeutronServer_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NeutronServer_descriptor_,
      NeutronServer::default_instance_,
      NeutronServer_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NeutronServer, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NeutronServer, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(NeutronServer));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_OpenStack_2eNeutronServer_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NeutronServer_descriptor_, &NeutronServer::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_OpenStack_2eNeutronServer_2eproto() {
  delete NeutronServer::default_instance_;
  delete NeutronServer_reflection_;
}

void protobuf_AddDesc_OpenStack_2eNeutronServer_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::cloudos::config::os::protobuf_AddDesc_OS_2eNetwork_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\035OpenStack.NeutronServer.proto\022\030cloudos"
    ".config.openstack\032\020OS.Network.proto\"n\n\rN"
    "eutronServer\022\017\n\007host_ip\030\002 \001(\t\022\026\n\016public_"
    "ip_pool\030\006 \001(\t\0224\n\014ssl_settings\030\024 \001(\0132\036.cl"
    "oudos.config.os.SSLSettings", 187);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "OpenStack.NeutronServer.proto", &protobuf_RegisterTypes);
  NeutronServer::default_instance_ = new NeutronServer();
  NeutronServer::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_OpenStack_2eNeutronServer_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_OpenStack_2eNeutronServer_2eproto {
  StaticDescriptorInitializer_OpenStack_2eNeutronServer_2eproto() {
    protobuf_AddDesc_OpenStack_2eNeutronServer_2eproto();
  }
} static_descriptor_initializer_OpenStack_2eNeutronServer_2eproto_;


// ===================================================================

#ifndef _MSC_VER
const int NeutronServer::kHostIpFieldNumber;
const int NeutronServer::kPublicIpPoolFieldNumber;
const int NeutronServer::kSslSettingsFieldNumber;
#endif  // !_MSC_VER

NeutronServer::NeutronServer()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void NeutronServer::InitAsDefaultInstance() {
  ssl_settings_ = const_cast< ::cloudos::config::os::SSLSettings*>(&::cloudos::config::os::SSLSettings::default_instance());
}

NeutronServer::NeutronServer(const NeutronServer& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void NeutronServer::SharedCtor() {
  _cached_size_ = 0;
  host_ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  public_ip_pool_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ssl_settings_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

NeutronServer::~NeutronServer() {
  SharedDtor();
}

void NeutronServer::SharedDtor() {
  if (host_ip_ != &::google::protobuf::internal::kEmptyString) {
    delete host_ip_;
  }
  if (public_ip_pool_ != &::google::protobuf::internal::kEmptyString) {
    delete public_ip_pool_;
  }
  if (this != default_instance_) {
    delete ssl_settings_;
  }
}

void NeutronServer::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* NeutronServer::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return NeutronServer_descriptor_;
}

const NeutronServer& NeutronServer::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_OpenStack_2eNeutronServer_2eproto();  return *default_instance_;
}

NeutronServer* NeutronServer::default_instance_ = NULL;

NeutronServer* NeutronServer::New() const {
  return new NeutronServer;
}

void NeutronServer::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (has_host_ip()) {
      if (host_ip_ != &::google::protobuf::internal::kEmptyString) {
        host_ip_->clear();
      }
    }
    if (has_public_ip_pool()) {
      if (public_ip_pool_ != &::google::protobuf::internal::kEmptyString) {
        public_ip_pool_->clear();
      }
    }
    if (has_ssl_settings()) {
      if (ssl_settings_ != NULL) ssl_settings_->::cloudos::config::os::SSLSettings::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool NeutronServer::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string host_ip = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_host_ip()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->host_ip().data(), this->host_ip().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(50)) goto parse_public_ip_pool;
        break;
      }
      
      // optional string public_ip_pool = 6;
      case 6: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_public_ip_pool:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_public_ip_pool()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->public_ip_pool().data(), this->public_ip_pool().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(162)) goto parse_ssl_settings;
        break;
      }
      
      // optional .cloudos.config.os.SSLSettings ssl_settings = 20;
      case 20: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_ssl_settings:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_ssl_settings()));
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }
      
      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void NeutronServer::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // optional string host_ip = 2;
  if (has_host_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->host_ip().data(), this->host_ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->host_ip(), output);
  }
  
  // optional string public_ip_pool = 6;
  if (has_public_ip_pool()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->public_ip_pool().data(), this->public_ip_pool().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      6, this->public_ip_pool(), output);
  }
  
  // optional .cloudos.config.os.SSLSettings ssl_settings = 20;
  if (has_ssl_settings()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      20, this->ssl_settings(), output);
  }
  
  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* NeutronServer::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // optional string host_ip = 2;
  if (has_host_ip()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->host_ip().data(), this->host_ip().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->host_ip(), target);
  }
  
  // optional string public_ip_pool = 6;
  if (has_public_ip_pool()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->public_ip_pool().data(), this->public_ip_pool().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->public_ip_pool(), target);
  }
  
  // optional .cloudos.config.os.SSLSettings ssl_settings = 20;
  if (has_ssl_settings()) {
    target = ::google::protobuf::internal::WireFormatLite::
      WriteMessageNoVirtualToArray(
        20, this->ssl_settings(), target);
  }
  
  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int NeutronServer::ByteSize() const {
  int total_size = 0;
  
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // optional string host_ip = 2;
    if (has_host_ip()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->host_ip());
    }
    
    // optional string public_ip_pool = 6;
    if (has_public_ip_pool()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->public_ip_pool());
    }
    
    // optional .cloudos.config.os.SSLSettings ssl_settings = 20;
    if (has_ssl_settings()) {
      total_size += 2 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->ssl_settings());
    }
    
  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void NeutronServer::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const NeutronServer* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const NeutronServer*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void NeutronServer::MergeFrom(const NeutronServer& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_host_ip()) {
      set_host_ip(from.host_ip());
    }
    if (from.has_public_ip_pool()) {
      set_public_ip_pool(from.public_ip_pool());
    }
    if (from.has_ssl_settings()) {
      mutable_ssl_settings()->::cloudos::config::os::SSLSettings::MergeFrom(from.ssl_settings());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void NeutronServer::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NeutronServer::CopyFrom(const NeutronServer& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NeutronServer::IsInitialized() const {
  
  return true;
}

void NeutronServer::Swap(NeutronServer* other) {
  if (other != this) {
    std::swap(host_ip_, other->host_ip_);
    std::swap(public_ip_pool_, other->public_ip_pool_);
    std::swap(ssl_settings_, other->ssl_settings_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata NeutronServer::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = NeutronServer_descriptor_;
  metadata.reflection = NeutronServer_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace openstack
}  // namespace config
}  // namespace cloudos

// @@protoc_insertion_point(global_scope)
