// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OpenStack.NovaMetadataClient.proto

#ifndef PROTOBUF_OpenStack_2eNovaMetadataClient_2eproto__INCLUDED
#define PROTOBUF_OpenStack_2eNovaMetadataClient_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

namespace cloudos {
namespace config {
namespace openstack {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_OpenStack_2eNovaMetadataClient_2eproto();
void protobuf_AssignDesc_OpenStack_2eNovaMetadataClient_2eproto();
void protobuf_ShutdownFile_OpenStack_2eNovaMetadataClient_2eproto();

class NovaMetadataClient;

// ===================================================================

class NovaMetadataClient : public ::google::protobuf::Message {
 public:
  NovaMetadataClient();
  virtual ~NovaMetadataClient();
  
  NovaMetadataClient(const NovaMetadataClient& from);
  
  inline NovaMetadataClient& operator=(const NovaMetadataClient& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const NovaMetadataClient& default_instance();
  
  void Swap(NovaMetadataClient* other);
  
  // implements Message ----------------------------------------------
  
  NovaMetadataClient* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const NovaMetadataClient& from);
  void MergeFrom(const NovaMetadataClient& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional uint32 port = 2;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 2;
  inline ::google::protobuf::uint32 port() const;
  inline void set_port(::google::protobuf::uint32 value);
  
  // optional string ip = 6;
  inline bool has_ip() const;
  inline void clear_ip();
  static const int kIpFieldNumber = 6;
  inline const ::std::string& ip() const;
  inline void set_ip(const ::std::string& value);
  inline void set_ip(const char* value);
  inline void set_ip(const char* value, size_t size);
  inline ::std::string* mutable_ip();
  inline ::std::string* release_ip();
  
  // @@protoc_insertion_point(class_scope:cloudos.config.openstack.NovaMetadataClient)
 private:
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_ip();
  inline void clear_has_ip();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::std::string* ip_;
  ::google::protobuf::uint32 port_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_OpenStack_2eNovaMetadataClient_2eproto();
  friend void protobuf_AssignDesc_OpenStack_2eNovaMetadataClient_2eproto();
  friend void protobuf_ShutdownFile_OpenStack_2eNovaMetadataClient_2eproto();
  
  void InitAsDefaultInstance();
  static NovaMetadataClient* default_instance_;
};
// ===================================================================


// ===================================================================

// NovaMetadataClient

// optional uint32 port = 2;
inline bool NovaMetadataClient::has_port() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void NovaMetadataClient::set_has_port() {
  _has_bits_[0] |= 0x00000001u;
}
inline void NovaMetadataClient::clear_has_port() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void NovaMetadataClient::clear_port() {
  port_ = 0u;
  clear_has_port();
}
inline ::google::protobuf::uint32 NovaMetadataClient::port() const {
  return port_;
}
inline void NovaMetadataClient::set_port(::google::protobuf::uint32 value) {
  set_has_port();
  port_ = value;
}

// optional string ip = 6;
inline bool NovaMetadataClient::has_ip() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void NovaMetadataClient::set_has_ip() {
  _has_bits_[0] |= 0x00000002u;
}
inline void NovaMetadataClient::clear_has_ip() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void NovaMetadataClient::clear_ip() {
  if (ip_ != &::google::protobuf::internal::kEmptyString) {
    ip_->clear();
  }
  clear_has_ip();
}
inline const ::std::string& NovaMetadataClient::ip() const {
  return *ip_;
}
inline void NovaMetadataClient::set_ip(const ::std::string& value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
}
inline void NovaMetadataClient::set_ip(const char* value) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  ip_->assign(value);
}
inline void NovaMetadataClient::set_ip(const char* value, size_t size) {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  ip_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* NovaMetadataClient::mutable_ip() {
  set_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    ip_ = new ::std::string;
  }
  return ip_;
}
inline ::std::string* NovaMetadataClient::release_ip() {
  clear_has_ip();
  if (ip_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = ip_;
    ip_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace openstack
}  // namespace config
}  // namespace cloudos

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_OpenStack_2eNovaMetadataClient_2eproto__INCLUDED
